services:
  - type: web
    name: todo-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /

databases:
  - name: todo-db
    databaseName: todo
    user: todo_user
    plan: free
